version: '3.8'
services:
    sbss1:
        image: cvex/sdvsm:v1
        container_name: sbss1
        privileged: true
        volumes:
            - "/home/sbss/volume/sbss1/keepalived:/etc/keepalived"
        networks:
            0_sbss_network:
                ipv4_address: 10.229.244.181
            1_sbss_network:
                ipv4_address: 192.168.1.181
            2_sbss_network:
                ipv4_address: 192.168.2.181
            3_sbss_network:
                ipv4_address: 192.168.3.181
    sbss2:
        image: cvex/sdvsm:v1
        container_name: sbss2
        privileged: true
        volumes:
            - "/home/sbss/volume/sbss2/keepalived:/etc/keepalived"
        networks:
            0_sbss_network:
                ipv4_address: 10.229.244.182
            1_sbss_network:
                ipv4_address: 192.168.1.182
            2_sbss_network:
                ipv4_address: 192.168.2.182
            3_sbss_network:
                ipv4_address: 192.168.3.182

networks:
    0_sbss_network:
        name: 0_sbss_network
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet: 10.229.244.0/24
    1_sbss_network:
        name: 1_sbss_network
        driver: macvlan
        driver_opts:
            parent: eth1
        ipam:
            config:
                - subnet: 192.168.1.0/24
    2_sbss_network:
        name: 2_sbss_network
        driver: macvlan
        driver_opts:
            parent: eth2
        ipam:
            config:
                - subnet: 192.168.2.0/24
    3_sbss_network:
        name: 3_sbss_network
        driver: macvlan
        driver_opts:
            parent: eth3
        ipam:
            config:
                - subnet: 192.168.3.0/24

