version: '3.8'
services:
    sbss1:
        image: cvex/sdvsm:v1
        container_name: sbss1
        privileged: true
        volumes:
            - "/home/sbss/volume/sbss1/keepalived:/etc/keepalived"
        networks:
            0_sbss_network:
                ipv4_address: 10.229.244.171
            1_sbss_network:
                ipv4_address: 192.168.1.171
            2_sbss_network:
                ipv4_address: 192.168.2.171
            3_sbss_network:
                ipv4_address: 192.168.3.171
    sbss2:
        image: cvex/sdvsm:v1
        container_name: sbss2
        privileged: true
        volumes:
            - "/home/sbss/volume/sbss2/keepalived:/etc/keepalived"
        networks:
            0_sbss_network:
                ipv4_address: 10.229.244.172
            1_sbss_network:
                ipv4_address: 192.168.1.172
            2_sbss_network:
                ipv4_address: 192.168.2.172
            3_sbss_network:
                ipv4_address: 192.168.3.172

networks:
    0_sbss_network:
        name: 0_sbss_network
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet: 10.229.244.0/24
    1_sbss_network:
        name: 1_sbss_network
        driver: macvlan
        driver_opts:
            parent: eth1
        ipam:
            config:
                - subnet: 192.168.1.0/24
    2_sbss_network:
        name: 2_sbss_network
        driver: macvlan
        driver_opts:
            parent: eth2
        ipam:
            config:
                - subnet: 192.168.2.0/24
    3_sbss_network:
        name: 3_sbss_network
        driver: macvlan
        driver_opts:
            parent: eth3
        ipam:
            config:
                - subnet: 192.168.3.0/24

